import type { Metadata } from "next";
import { Provider } from "react-redux";
import { config } from "@fortawesome/fontawesome-svg-core";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Sidebar from "./(components)/sidebar";
import { store } from "@/store";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const RootLayout: React.FC<
  Readonly<{
    children: React.ReactNode;
  }>
> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <div className="flex h-screen w-screen">
            <div className="h-full w-2/12 shadow-md p-3">
              <Sidebar />
            </div>
            <div className="h-full w-10/12">
              <div className="h-14 w-full shadow-md">Header</div>
              <main>{children}</main>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
