import type { Metadata } from "next";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen w-screen">
          <div className="h-full w-2/12 shadow-md">Sidebar</div>
          <div className="h-full w-10/12">
            <div className="h-14 w-full shadow-md">Header</div>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
