import {
  faAward,
  faBoltLightning,
  faCalendarAlt,
  faCalendarDay,
  faCalendarWeek,
  faContactBook,
  faDatabase,
  faHome,
  faInbox,
  faLayerGroup,
  faLightbulb,
  faMagicWandSparkles,
  faPeopleGroup,
  faPersonBooth,
  faPuzzlePiece,
  faRankingStar,
  faShop,
  faStar,
  faStarOfLife,
  faVestPatches,
} from '@fortawesome/free-solid-svg-icons';
import type { IMenuList } from '../types/menu-type';

export const MenuList: IMenuList[] = [
  {
    label: 'Explore',
    icon: faHome,
    href: '/',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: 'Awards',
    icon: faAward,
    enabled: true,
    roles: [1, 2, 3],
    items: [
      {
        label: 'Nominees',
        icon: faPeopleGroup,
        enabled: true,
        roles: [1, 2],
        items: [
          {
            label: 'Most Rated',
            icon: faStar,
            href: '/awards/nominees/most-rated',
            enabled: true,
            roles: [1, 2],
          },
          {
            label: 'Competitive',
            icon: faStarOfLife,
            href: '/awards/nominees/competitive',
            enabled: true,
            roles: [1, 2],
          },
        ],
      },
      {
        label: 'Day Highlights',
        icon: faCalendarDay,
        enabled: true,
        roles: [1, 2, 3],
        items: [
          {
            label: 'Most Popular',
            icon: faBoltLightning,
            href: '/awards/day-highlights/popular',
            enabled: true,
            roles: [1, 2],
          },
          {
            label: 'Most Creative',
            icon: faLightbulb,
            href: '/awards/day-highlights/creative',
            enabled: true,
            roles: [1, 2, 3],
          },
          {
            label: 'Most Innovative',
            icon: faMagicWandSparkles,
            href: '/awards/day-highlights/innovative',
            enabled: true,
            roles: [1, 2, 3],
          },
        ],
      },
      {
        label: 'Month Highlights',
        icon: faCalendarWeek,
        enabled: true,
        roles: [1, 2, 3],
        items: [
          {
            label: 'Most Popular',
            icon: faBoltLightning,
            href: '/awards/month-highlights/popular',
            enabled: true,
            roles: [1, 2],
          },
          {
            label: 'Most Creative',
            icon: faLightbulb,
            href: '/awards/month-highlights/creative',
            enabled: true,
            roles: [1, 2, 3],
          },
          {
            label: 'Most Innovative',
            icon: faMagicWandSparkles,
            href: '/awards/month-highlights/innovative',
            enabled: true,
            roles: [1, 2, 3],
          },
        ],
      },
      {
        label: 'Year Highlights',
        icon: faCalendarAlt,
        enabled: true,
        roles: [1],
        items: [
          {
            label: 'Most Popular',
            icon: faBoltLightning,
            href: '/awards/year-highlights/popular',
            enabled: true,
            roles: [1],
          },
          {
            label: 'Most Creative',
            icon: faLightbulb,
            href: '/awards/year-highlights/creative',
            enabled: true,
            roles: [1],
          },
          {
            label: 'Most Innovative',
            icon: faMagicWandSparkles,
            href: '/awards/year-highlights/innovative',
            enabled: true,
            roles: [1],
          },
        ],
      },
    ],
  },
  {
    label: 'Categories',
    icon: faLayerGroup,
    enabled: true,
    roles: [1, 2, 3],
    items: [
      {
        label: 'E-Commerce',
        icon: faShop,
        href: '/categories/e-commerce',
        enabled: true,
        roles: [1, 2, 3],
      },
      {
        label: 'Gaming',
        icon: faPuzzlePiece,
        href: '/categories/gaming',
        enabled: true,
        roles: [1, 2],
      },
      {
        label: 'Fashion',
        icon: faVestPatches,
        href: '/categories/fashion',
        enabled: true,
        roles: [1, 2, 3],
      },
    ],
  },
  {
    label: 'Participate',
    icon: faPersonBooth,
    href: '/participate',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: 'My Rank',
    icon: faRankingStar,
    href: '/my-rank',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: 'About',
    icon: faInbox,
    href: '/about',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: 'Contact-Us',
    icon: faContactBook,
    href: '/contact-us',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: 'Total-Submissions',
    icon: faDatabase,
    href: '/submissions',
    enabled: true,
    roles: [1],
  },
];
