import type { IMenuList } from '@/types/menu-type';
import {
  faAward,
  faBoltLightning,
  faCalendarAlt,
  faCalendarDay,
  faCalendarWeek,
  faContactBook,
  faDatabase,
  faHome,
  faInbox,
  faLayerGroup,
  faLightbulb,
  faMagicWandSparkles,
  faPeopleGroup,
  faPersonBooth,
  faPuzzlePiece,
  faRankingStar,
  faShop,
  faStar,
  faStarOfLife,
  faVestPatches,
} from '@fortawesome/free-solid-svg-icons';
import { t } from 'i18next';

export const MenuList: IMenuList[] = [
  {
    label: t('explore.title'),
    icon: faHome,
    href: '/',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: t('awards.title'),
    icon: faAward,
    enabled: true,
    roles: [1, 2, 3],
    items: [
      {
        label: t('awards.nominees.title'),
        icon: faPeopleGroup,
        enabled: true,
        roles: [1, 2],
        items: [
          {
            label: t('awards.nominees.mostRated.title'),
            icon: faStar,
            href: '/awards/nominees/most-rated',
            enabled: true,
            roles: [1, 2],
          },
          {
            label: t('awards.nominees.competitive.title'),
            icon: faStarOfLife,
            href: '/awards/nominees/competitive',
            enabled: true,
            roles: [1, 2],
          },
        ],
      },
      {
        label: t('awards.dayHighlights.title'),
        icon: faCalendarDay,
        enabled: true,
        roles: [1, 2, 3],
        items: [
          {
            label: t('awards.dayHighlights.popular.title'),
            icon: faBoltLightning,
            href: '/awards/day-highlights/popular',
            enabled: true,
            roles: [1, 2],
          },
          {
            label: t('awards.dayHighlights.creative.title'),
            icon: faLightbulb,
            href: '/awards/day-highlights/creative',
            enabled: true,
            roles: [1, 2, 3],
          },
          {
            label: t('awards.dayHighlights.innovative.title'),
            icon: faMagicWandSparkles,
            href: '/awards/day-highlights/innovative',
            enabled: true,
            roles: [1, 2, 3],
          },
        ],
      },
      {
        label: t('awards.monthHighlights.title'),
        icon: faCalendarWeek,
        enabled: true,
        roles: [1, 2, 3],
        items: [
          {
            label: t('awards.monthHighlights.popular.title'),
            icon: faBoltLightning,
            href: '/awards/month-highlights/popular',
            enabled: true,
            roles: [1, 2],
          },
          {
            label: t('awards.monthHighlights.creative.title'),
            icon: faLightbulb,
            href: '/awards/month-highlights/creative',
            enabled: true,
            roles: [1, 2, 3],
          },
          {
            label: t('awards.monthHighlights.innovative.title'),
            icon: faMagicWandSparkles,
            href: '/awards/month-highlights/innovative',
            enabled: true,
            roles: [1, 2, 3],
          },
        ],
      },
      {
        label: t('awards.yearHighlights.title'),
        icon: faCalendarAlt,
        enabled: true,
        roles: [1],
        items: [
          {
            label: t('awards.yearHighlights.popular.title'),
            icon: faBoltLightning,
            href: '/awards/year-highlights/popular',
            enabled: true,
            roles: [1],
          },
          {
            label: t('awards.yearHighlights.creative.title'),
            icon: faLightbulb,
            href: '/awards/year-highlights/creative',
            enabled: true,
            roles: [1],
          },
          {
            label: t('awards.yearHighlights.innovative.title'),
            icon: faMagicWandSparkles,
            href: '/awards/year-highlights/innovative',
            enabled: true,
            roles: [1],
          },
        ],
      },
    ],
  },
  {
    label: t('categories.title'),
    icon: faLayerGroup,
    enabled: true,
    roles: [1, 2, 3],
    items: [
      {
        label: t('categories.e-commerce.title'),
        icon: faShop,
        href: '/categories/e-commerce',
        enabled: true,
        roles: [1, 2, 3],
      },
      {
        label: t('categories.gaming.title'),
        icon: faPuzzlePiece,
        href: '/categories/gaming',
        enabled: true,
        roles: [1, 2],
      },
      {
        label: t('categories.fashion.title'),
        icon: faVestPatches,
        href: '/categories/fashion',
        enabled: true,
        roles: [1, 2, 3],
      },
    ],
  },
  {
    label: t('participate.title'),
    icon: faPersonBooth,
    href: '/participate',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: t('my-rank.title'),
    icon: faRankingStar,
    href: '/my-rank',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: t('about.title'),
    icon: faInbox,
    href: '/about',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: t('contact-us.title'),
    icon: faContactBook,
    href: '/contact-us',
    enabled: true,
    roles: [1, 2, 3],
  },
  {
    label: t('submissions.title'),
    icon: faDatabase,
    href: '/submissions',
    enabled: true,
    roles: [1],
  },
];
